// Copyright 2024 Eryx <evorui at gmail dot com>, All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v6.32.1
// source: lynkui/lynkui.proto

package lynkui

import (
	lynkapi "github.com/lynkdb/lynkapi/go/lynkapi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Project struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
}

func (x *Project) Reset() {
	*x = Project{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// frontend components
type Pagelet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind                string            `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty" toml:"kind,omitempty" yaml:"kind,omitempty"`
	Name                string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	DisplayName         string            `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty" toml:"display_name,omitempty" yaml:"display_name,omitempty"`
	Args                map[string]string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" toml:"args,omitempty" yaml:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Output              string            `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty" toml:"output,omitempty" yaml:"output,omitempty"`
	Template            *TemplateSpec     `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty" toml:"template,omitempty" yaml:"template,omitempty"`
	Datalet             *DataletSpec      `protobuf:"bytes,7,opt,name=datalet,proto3" json:"datalet,omitempty" toml:"datalet,omitempty" yaml:"datalet,omitempty"`
	NextPagelets        []*Pagelet_Next   `protobuf:"bytes,9,rep,name=next_pagelets,json=nextPagelets,proto3" json:"next_pagelets,omitempty" toml:"next_pagelets,omitempty" yaml:"next_pagelets,omitempty"`
	Event               *Pagelet_Event    `protobuf:"bytes,10,opt,name=event,proto3" json:"event,omitempty" toml:"event,omitempty" yaml:"event,omitempty"`
	PostTasklets        []*Tasklet        `protobuf:"bytes,32,rep,name=post_tasklets,json=postTasklets,proto3" json:"post_tasklets,omitempty" toml:"post_tasklets,omitempty" yaml:"post_tasklets,omitempty"`
	ExpDataCreateEnable bool              `protobuf:"varint,48,opt,name=exp_data_create_enable,json=expDataCreateEnable,proto3" json:"exp_data_create_enable,omitempty" toml:"exp_data_create_enable,omitempty" yaml:"exp_data_create_enable,omitempty"`
	ExpDataUpdateEnable bool              `protobuf:"varint,49,opt,name=exp_data_update_enable,json=expDataUpdateEnable,proto3" json:"exp_data_update_enable,omitempty" toml:"exp_data_update_enable,omitempty" yaml:"exp_data_update_enable,omitempty"`
}

func (x *Pagelet) Reset() {
	*x = Pagelet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagelet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagelet) ProtoMessage() {}

func (x *Pagelet) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagelet.ProtoReflect.Descriptor instead.
func (*Pagelet) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{1}
}

func (x *Pagelet) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Pagelet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pagelet) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Pagelet) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Pagelet) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Pagelet) GetTemplate() *TemplateSpec {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *Pagelet) GetDatalet() *DataletSpec {
	if x != nil {
		return x.Datalet
	}
	return nil
}

func (x *Pagelet) GetNextPagelets() []*Pagelet_Next {
	if x != nil {
		return x.NextPagelets
	}
	return nil
}

func (x *Pagelet) GetEvent() *Pagelet_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Pagelet) GetPostTasklets() []*Tasklet {
	if x != nil {
		return x.PostTasklets
	}
	return nil
}

func (x *Pagelet) GetExpDataCreateEnable() bool {
	if x != nil {
		return x.ExpDataCreateEnable
	}
	return false
}

func (x *Pagelet) GetExpDataUpdateEnable() bool {
	if x != nil {
		return x.ExpDataUpdateEnable
	}
	return false
}

type Tasklet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NavClick string `protobuf:"bytes,4,opt,name=nav_click,json=navClick,proto3" json:"nav_click,omitempty" toml:"nav_click,omitempty" yaml:"nav_click,omitempty"`
}

func (x *Tasklet) Reset() {
	*x = Tasklet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tasklet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tasklet) ProtoMessage() {}

func (x *Tasklet) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tasklet.ProtoReflect.Descriptor instead.
func (*Tasklet) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{2}
}

func (x *Tasklet) GetNavClick() string {
	if x != nil {
		return x.NavClick
	}
	return ""
}

type DataLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tables    []*DataLayout_VirtualTable `protobuf:"bytes,9,rep,name=tables,proto3" json:"tables,omitempty" toml:"tables,omitempty" yaml:"tables,omitempty"`
	Connects  []*lynkapi.DataConnect     `protobuf:"bytes,12,rep,name=connects,proto3" json:"connects,omitempty" toml:"connects,omitempty" yaml:"connects,omitempty"`
	Instances []*lynkapi.DataInstance    `protobuf:"bytes,13,rep,name=instances,proto3" json:"instances,omitempty" toml:"instances,omitempty" yaml:"instances,omitempty"`
}

func (x *DataLayout) Reset() {
	*x = DataLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataLayout) ProtoMessage() {}

func (x *DataLayout) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataLayout.ProtoReflect.Descriptor instead.
func (*DataLayout) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{3}
}

func (x *DataLayout) GetTables() []*DataLayout_VirtualTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *DataLayout) GetConnects() []*lynkapi.DataConnect {
	if x != nil {
		return x.Connects
	}
	return nil
}

func (x *DataLayout) GetInstances() []*lynkapi.DataInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type DataletSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string instance_name = 6;
	TableName string                    `protobuf:"bytes,7,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty" toml:"table_name,omitempty" yaml:"table_name,omitempty"`
	Filter    *lynkapi.DataQuery_Filter `protobuf:"bytes,11,opt,name=filter,proto3" json:"filter,omitempty" toml:"filter,omitempty" yaml:"filter,omitempty"`
	Query     *lynkapi.DataQuery        `protobuf:"bytes,8,opt,name=query,proto3" json:"query,omitempty" toml:"query,omitempty" yaml:"query,omitempty"`
	TableSpec *lynkapi.TableSpec        `protobuf:"bytes,10,opt,name=table_spec,json=tableSpec,proto3" json:"table_spec,omitempty" toml:"table_spec,omitempty" yaml:"table_spec,omitempty"`
	List      *DataletSpec_ListAction   `protobuf:"bytes,12,opt,name=list,proto3" json:"list,omitempty" toml:"list,omitempty" yaml:"list,omitempty"`
}

func (x *DataletSpec) Reset() {
	*x = DataletSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataletSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataletSpec) ProtoMessage() {}

func (x *DataletSpec) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataletSpec.ProtoReflect.Descriptor instead.
func (*DataletSpec) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{4}
}

func (x *DataletSpec) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DataletSpec) GetFilter() *lynkapi.DataQuery_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DataletSpec) GetQuery() *lynkapi.DataQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *DataletSpec) GetTableSpec() *lynkapi.TableSpec {
	if x != nil {
		return x.TableSpec
	}
	return nil
}

func (x *DataletSpec) GetList() *DataletSpec_ListAction {
	if x != nil {
		return x.List
	}
	return nil
}

type TemplateSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout *TemplateLayout `protobuf:"bytes,9,opt,name=layout,proto3" json:"layout,omitempty" toml:"layout,omitempty" yaml:"layout,omitempty"`
	Nav    *TemplateNav    `protobuf:"bytes,10,opt,name=nav,proto3" json:"nav,omitempty" toml:"nav,omitempty" yaml:"nav,omitempty"`
	Table  *TemplateTable  `protobuf:"bytes,11,opt,name=table,proto3" json:"table,omitempty" toml:"table,omitempty" yaml:"table,omitempty"`
	Html   *TemplateHtml   `protobuf:"bytes,31,opt,name=html,proto3" json:"html,omitempty" toml:"html,omitempty" yaml:"html,omitempty"`
}

func (x *TemplateSpec) Reset() {
	*x = TemplateSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSpec) ProtoMessage() {}

func (x *TemplateSpec) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSpec.ProtoReflect.Descriptor instead.
func (*TemplateSpec) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{5}
}

func (x *TemplateSpec) GetLayout() *TemplateLayout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *TemplateSpec) GetNav() *TemplateNav {
	if x != nil {
		return x.Nav
	}
	return nil
}

func (x *TemplateSpec) GetTable() *TemplateTable {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *TemplateSpec) GetHtml() *TemplateHtml {
	if x != nil {
		return x.Html
	}
	return nil
}

type TemplateLayout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Align      string            `protobuf:"bytes,3,opt,name=align,proto3" json:"align,omitempty" toml:"align,omitempty" yaml:"align,omitempty"`
	Width      string            `protobuf:"bytes,4,opt,name=width,proto3" json:"width,omitempty" toml:"width,omitempty" yaml:"width,omitempty"`
	Height     string            `protobuf:"bytes,5,opt,name=height,proto3" json:"height,omitempty" toml:"height,omitempty" yaml:"height,omitempty"`
	StyleClass string            `protobuf:"bytes,12,opt,name=style_class,json=styleClass,proto3" json:"style_class,omitempty" toml:"style_class,omitempty" yaml:"style_class,omitempty"`
	Options    map[string]string `protobuf:"bytes,13,rep,name=options,proto3" json:"options,omitempty" toml:"options,omitempty" yaml:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Rows       []*TemplateLayout `protobuf:"bytes,14,rep,name=rows,proto3" json:"rows,omitempty" toml:"rows,omitempty" yaml:"rows,omitempty"`
	Cols       []*TemplateLayout `protobuf:"bytes,15,rep,name=cols,proto3" json:"cols,omitempty" toml:"cols,omitempty" yaml:"cols,omitempty"`
}

func (x *TemplateLayout) Reset() {
	*x = TemplateLayout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateLayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateLayout) ProtoMessage() {}

func (x *TemplateLayout) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateLayout.ProtoReflect.Descriptor instead.
func (*TemplateLayout) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{6}
}

func (x *TemplateLayout) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateLayout) GetAlign() string {
	if x != nil {
		return x.Align
	}
	return ""
}

func (x *TemplateLayout) GetWidth() string {
	if x != nil {
		return x.Width
	}
	return ""
}

func (x *TemplateLayout) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *TemplateLayout) GetStyleClass() string {
	if x != nil {
		return x.StyleClass
	}
	return ""
}

func (x *TemplateLayout) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *TemplateLayout) GetRows() []*TemplateLayout {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *TemplateLayout) GetCols() []*TemplateLayout {
	if x != nil {
		return x.Cols
	}
	return nil
}

type TemplateNav struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Display string              `protobuf:"bytes,1,opt,name=display,proto3" json:"display,omitempty" toml:"display,omitempty" yaml:"display,omitempty" x_enums:"flex-column"`
	Items   []*TemplateNav_Item `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty" toml:"items,omitempty" yaml:"items,omitempty"`
}

func (x *TemplateNav) Reset() {
	*x = TemplateNav{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateNav) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateNav) ProtoMessage() {}

func (x *TemplateNav) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateNav.ProtoReflect.Descriptor instead.
func (*TemplateNav) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{7}
}

func (x *TemplateNav) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *TemplateNav) GetItems() []*TemplateNav_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type TemplateHtml struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty" toml:"file,omitempty" yaml:"file,omitempty"`
	Html string `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty" toml:"html,omitempty" yaml:"html,omitempty"`
}

func (x *TemplateHtml) Reset() {
	*x = TemplateHtml{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateHtml) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateHtml) ProtoMessage() {}

func (x *TemplateHtml) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateHtml.ProtoReflect.Descriptor instead.
func (*TemplateHtml) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{8}
}

func (x *TemplateHtml) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *TemplateHtml) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

type TemplateTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TemplateTable) Reset() {
	*x = TemplateTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateTable) ProtoMessage() {}

func (x *TemplateTable) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateTable.ProtoReflect.Descriptor instead.
func (*TemplateTable) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{9}
}

type Pagelet_Next struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
}

func (x *Pagelet_Next) Reset() {
	*x = Pagelet_Next{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagelet_Next) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagelet_Next) ProtoMessage() {}

func (x *Pagelet_Next) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagelet_Next.ProtoReflect.Descriptor instead.
func (*Pagelet_Next) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Pagelet_Next) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Pagelet_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Pagelet string `protobuf:"bytes,2,opt,name=pagelet,proto3" json:"pagelet,omitempty" toml:"pagelet,omitempty" yaml:"pagelet,omitempty"`
}

func (x *Pagelet_Event) Reset() {
	*x = Pagelet_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagelet_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagelet_Event) ProtoMessage() {}

func (x *Pagelet_Event) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagelet_Event.ProtoReflect.Descriptor instead.
func (*Pagelet_Event) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Pagelet_Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pagelet_Event) GetPagelet() string {
	if x != nil {
		return x.Pagelet
	}
	return ""
}

type DataLayout_VirtualTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	// string model = 2;
	RefInstance string `protobuf:"bytes,8,opt,name=ref_instance,json=refInstance,proto3" json:"ref_instance,omitempty" toml:"ref_instance,omitempty" yaml:"ref_instance,omitempty"`
	RefTable    string `protobuf:"bytes,9,opt,name=ref_table,json=refTable,proto3" json:"ref_table,omitempty" toml:"ref_table,omitempty" yaml:"ref_table,omitempty"`
}

func (x *DataLayout_VirtualTable) Reset() {
	*x = DataLayout_VirtualTable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataLayout_VirtualTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataLayout_VirtualTable) ProtoMessage() {}

func (x *DataLayout_VirtualTable) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataLayout_VirtualTable.ProtoReflect.Descriptor instead.
func (*DataLayout_VirtualTable) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DataLayout_VirtualTable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataLayout_VirtualTable) GetRefInstance() string {
	if x != nil {
		return x.RefInstance
	}
	return ""
}

func (x *DataLayout_VirtualTable) GetRefTable() string {
	if x != nil {
		return x.RefTable
	}
	return ""
}

type DataletSpec_DisplayField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
}

func (x *DataletSpec_DisplayField) Reset() {
	*x = DataletSpec_DisplayField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataletSpec_DisplayField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataletSpec_DisplayField) ProtoMessage() {}

func (x *DataletSpec_DisplayField) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataletSpec_DisplayField.ProtoReflect.Descriptor instead.
func (*DataletSpec_DisplayField) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DataletSpec_DisplayField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DataletSpec_ListAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DisplayFields []string                      `protobuf:"bytes,2,rep,name=display_fields,json=displayFields,proto3" json:"display_fields,omitempty" toml:"display_fields,omitempty" yaml:"display_fields,omitempty"`
	Filter        *lynkapi.DataQuery_Filter     `protobuf:"bytes,11,opt,name=filter,proto3" json:"filter,omitempty" toml:"filter,omitempty" yaml:"filter,omitempty"`
	Sort          *lynkapi.DataQuery_SortFilter `protobuf:"bytes,12,opt,name=sort,proto3" json:"sort,omitempty" toml:"sort,omitempty" yaml:"sort,omitempty"`
}

func (x *DataletSpec_ListAction) Reset() {
	*x = DataletSpec_ListAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataletSpec_ListAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataletSpec_ListAction) ProtoMessage() {}

func (x *DataletSpec_ListAction) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataletSpec_ListAction.ProtoReflect.Descriptor instead.
func (*DataletSpec_ListAction) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{4, 1}
}

func (x *DataletSpec_ListAction) GetDisplayFields() []string {
	if x != nil {
		return x.DisplayFields
	}
	return nil
}

func (x *DataletSpec_ListAction) GetFilter() *lynkapi.DataQuery_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *DataletSpec_ListAction) GetSort() *lynkapi.DataQuery_SortFilter {
	if x != nil {
		return x.Sort
	}
	return nil
}

type TemplateNav_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" toml:"name,omitempty" yaml:"name,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty" toml:"title,omitempty" yaml:"title,omitempty"`
}

func (x *TemplateNav_Item) Reset() {
	*x = TemplateNav_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lynkui_lynkui_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemplateNav_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateNav_Item) ProtoMessage() {}

func (x *TemplateNav_Item) ProtoReflect() protoreflect.Message {
	mi := &file_lynkui_lynkui_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateNav_Item.ProtoReflect.Descriptor instead.
func (*TemplateNav_Item) Descriptor() ([]byte, []int) {
	return file_lynkui_lynkui_proto_rawDescGZIP(), []int{7, 0}
}

func (x *TemplateNav_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateNav_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_lynkui_lynkui_proto protoreflect.FileDescriptor

var file_lynkui_lynkui_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x1a, 0x12, 0x6c,
	0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x31, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x90, 0x05, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x75, 0x69, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x74, 0x2e, 0x41, 0x72, 0x67, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x30, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61,
	0x6c, 0x65, 0x74, 0x12, 0x39, 0x0a, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65,
	0x6c, 0x65, 0x74, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x79, 0x6e,
	0x6b, 0x75, 0x69, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x74, 0x2e, 0x4e, 0x65, 0x78, 0x74,
	0x52, 0x0c, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x74, 0x73, 0x12, 0x2b,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x74, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x0d, 0x70,
	0x6f, 0x73, 0x74, 0x5f, 0x74, 0x61, 0x73, 0x6b, 0x6c, 0x65, 0x74, 0x73, 0x18, 0x20, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x6c, 0x65, 0x74, 0x52, 0x0c, 0x70, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x6c, 0x65, 0x74,
	0x73, 0x12, 0x33, 0x0a, 0x16, 0x65, 0x78, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x30, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x13, 0x65, 0x78, 0x70, 0x44, 0x61, 0x74, 0x61, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x16, 0x65, 0x78, 0x70, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65,
	0x18, 0x31, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x65, 0x78, 0x70, 0x44, 0x61, 0x74, 0x61, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x1a, 0x37, 0x0a, 0x09, 0x41,
	0x72, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x1a, 0x1a, 0x0a, 0x04, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x1a, 0x35, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x61, 0x67, 0x65, 0x6c, 0x65, 0x74, 0x22, 0x26, 0x0a, 0x07, 0x54, 0x61, 0x73, 0x6b, 0x6c,
	0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x61, 0x76, 0x5f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x76, 0x43, 0x6c, 0x69, 0x63, 0x6b, 0x22,
	0x90, 0x02, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x37,
	0x0a, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x09, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x1a, 0x62,
	0x0a, 0x0c, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x5f, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x66, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x22, 0xb0, 0x03, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74, 0x53, 0x70,
	0x65, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x31,
	0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x6c, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x1a, 0x22, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x99, 0x01, 0x0a, 0x0a, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0xbc, 0x01, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x2e, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x03, 0x6e, 0x61, 0x76, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x76, 0x52, 0x03, 0x6e, 0x61, 0x76, 0x12, 0x2b, 0x0a,
	0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x68, 0x74,
	0x6d, 0x6c, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75,
	0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x74, 0x6d, 0x6c, 0x52, 0x04,
	0x68, 0x74, 0x6d, 0x6c, 0x22, 0xdc, 0x02, 0x0a, 0x0e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x6c, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x67,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x12, 0x3d, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x2a, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x2a, 0x0a, 0x04, 0x63,
	0x6f, 0x6c, 0x73, 0x18, 0x0f, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x79, 0x6e, 0x6b,
	0x75, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x04, 0x63, 0x6f, 0x6c, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x89, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x4e, 0x61, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x2e, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c,
	0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x61,
	0x76, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x30, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22,
	0x36, 0x0a, 0x0c, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x48, 0x74, 0x6d, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x74, 0x6d, 0x6c, 0x22, 0x0f, 0x0a, 0x0d, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x2d, 0x48, 0x03, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x64, 0x62, 0x2f,
	0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69,
	0x3b, 0x6c, 0x79, 0x6e, 0x6b, 0x75, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lynkui_lynkui_proto_rawDescOnce sync.Once
	file_lynkui_lynkui_proto_rawDescData = file_lynkui_lynkui_proto_rawDesc
)

func file_lynkui_lynkui_proto_rawDescGZIP() []byte {
	file_lynkui_lynkui_proto_rawDescOnce.Do(func() {
		file_lynkui_lynkui_proto_rawDescData = protoimpl.X.CompressGZIP(file_lynkui_lynkui_proto_rawDescData)
	})
	return file_lynkui_lynkui_proto_rawDescData
}

var file_lynkui_lynkui_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_lynkui_lynkui_proto_goTypes = []interface{}{
	(*Project)(nil),                      // 0: lynkui.Project
	(*Pagelet)(nil),                      // 1: lynkui.Pagelet
	(*Tasklet)(nil),                      // 2: lynkui.Tasklet
	(*DataLayout)(nil),                   // 3: lynkui.DataLayout
	(*DataletSpec)(nil),                  // 4: lynkui.DataletSpec
	(*TemplateSpec)(nil),                 // 5: lynkui.TemplateSpec
	(*TemplateLayout)(nil),               // 6: lynkui.TemplateLayout
	(*TemplateNav)(nil),                  // 7: lynkui.TemplateNav
	(*TemplateHtml)(nil),                 // 8: lynkui.TemplateHtml
	(*TemplateTable)(nil),                // 9: lynkui.TemplateTable
	nil,                                  // 10: lynkui.Pagelet.ArgsEntry
	(*Pagelet_Next)(nil),                 // 11: lynkui.Pagelet.Next
	(*Pagelet_Event)(nil),                // 12: lynkui.Pagelet.Event
	(*DataLayout_VirtualTable)(nil),      // 13: lynkui.DataLayout.VirtualTable
	(*DataletSpec_DisplayField)(nil),     // 14: lynkui.DataletSpec.DisplayField
	(*DataletSpec_ListAction)(nil),       // 15: lynkui.DataletSpec.ListAction
	nil,                                  // 16: lynkui.TemplateLayout.OptionsEntry
	(*TemplateNav_Item)(nil),             // 17: lynkui.TemplateNav.Item
	(*lynkapi.DataConnect)(nil),          // 18: lynkapi.DataConnect
	(*lynkapi.DataInstance)(nil),         // 19: lynkapi.DataInstance
	(*lynkapi.DataQuery_Filter)(nil),     // 20: lynkapi.DataQuery.Filter
	(*lynkapi.DataQuery)(nil),            // 21: lynkapi.DataQuery
	(*lynkapi.TableSpec)(nil),            // 22: lynkapi.TableSpec
	(*lynkapi.DataQuery_SortFilter)(nil), // 23: lynkapi.DataQuery.SortFilter
}
var file_lynkui_lynkui_proto_depIdxs = []int32{
	10, // 0: lynkui.Pagelet.args:type_name -> lynkui.Pagelet.ArgsEntry
	5,  // 1: lynkui.Pagelet.template:type_name -> lynkui.TemplateSpec
	4,  // 2: lynkui.Pagelet.datalet:type_name -> lynkui.DataletSpec
	11, // 3: lynkui.Pagelet.next_pagelets:type_name -> lynkui.Pagelet.Next
	12, // 4: lynkui.Pagelet.event:type_name -> lynkui.Pagelet.Event
	2,  // 5: lynkui.Pagelet.post_tasklets:type_name -> lynkui.Tasklet
	13, // 6: lynkui.DataLayout.tables:type_name -> lynkui.DataLayout.VirtualTable
	18, // 7: lynkui.DataLayout.connects:type_name -> lynkapi.DataConnect
	19, // 8: lynkui.DataLayout.instances:type_name -> lynkapi.DataInstance
	20, // 9: lynkui.DataletSpec.filter:type_name -> lynkapi.DataQuery.Filter
	21, // 10: lynkui.DataletSpec.query:type_name -> lynkapi.DataQuery
	22, // 11: lynkui.DataletSpec.table_spec:type_name -> lynkapi.TableSpec
	15, // 12: lynkui.DataletSpec.list:type_name -> lynkui.DataletSpec.ListAction
	6,  // 13: lynkui.TemplateSpec.layout:type_name -> lynkui.TemplateLayout
	7,  // 14: lynkui.TemplateSpec.nav:type_name -> lynkui.TemplateNav
	9,  // 15: lynkui.TemplateSpec.table:type_name -> lynkui.TemplateTable
	8,  // 16: lynkui.TemplateSpec.html:type_name -> lynkui.TemplateHtml
	16, // 17: lynkui.TemplateLayout.options:type_name -> lynkui.TemplateLayout.OptionsEntry
	6,  // 18: lynkui.TemplateLayout.rows:type_name -> lynkui.TemplateLayout
	6,  // 19: lynkui.TemplateLayout.cols:type_name -> lynkui.TemplateLayout
	17, // 20: lynkui.TemplateNav.items:type_name -> lynkui.TemplateNav.Item
	20, // 21: lynkui.DataletSpec.ListAction.filter:type_name -> lynkapi.DataQuery.Filter
	23, // 22: lynkui.DataletSpec.ListAction.sort:type_name -> lynkapi.DataQuery.SortFilter
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_lynkui_lynkui_proto_init() }
func file_lynkui_lynkui_proto_init() {
	if File_lynkui_lynkui_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lynkui_lynkui_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Project); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagelet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tasklet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataletSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateLayout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateNav); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateHtml); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagelet_Next); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagelet_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataLayout_VirtualTable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataletSpec_DisplayField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataletSpec_ListAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lynkui_lynkui_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemplateNav_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lynkui_lynkui_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lynkui_lynkui_proto_goTypes,
		DependencyIndexes: file_lynkui_lynkui_proto_depIdxs,
		MessageInfos:      file_lynkui_lynkui_proto_msgTypes,
	}.Build()
	File_lynkui_lynkui_proto = out.File
	file_lynkui_lynkui_proto_rawDesc = nil
	file_lynkui_lynkui_proto_goTypes = nil
	file_lynkui_lynkui_proto_depIdxs = nil
}
